name: Deploy MkDocs Natively
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: 
            pip install mkdocs-material
            pip install mkdocs-awesome-pages-plugin 
          
      - name: Build Web Application
        run: mkdocs build --site-dir site
        
      - name: Disable Jekyll Extension Filtering
        run: touch site/.nojekyll
        
      - name: Setup GitHub Pages Environment
        uses: actions/configure-pages@v4
        
      - name: Upload Finished Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site # MkDocs outputs built files to 'site' by default

      - name: Deploy Live Pages Output
        uses: actions/deploy-pages@v4
